/*****************************************************************************************************************
 * Dll on Demaind Application Utility Class  - initially this class contains the callouts to get applicaiton data
 *
 * Change Log:
 *
 * 11/23/2022 - MRM Create class
 *******************************************************************************************************************/
public with sharing class AppUtility {

}