/*****************************************************************************************************************
 * Dll on Demaind (DD) EARCHIVE UTILITY CLASS
 *
 * Change Log:
 *
 *  10/26/2022 - MRM Created class
 *******************************************************************************************************************/
public with sharing class eArchiveUtils {


/************************************************************************************************************************************************
 * @getPrograms - gets the contract documents
 *
 * change log:
 *
 *
 * @return   return programList
 *****************************************************************************************************************************************************/
@AuraEnabled (Cacheable=true)
public static String getContractDocs(String ContractListViewTest){

	return null;
}

}