/**
 * @description       : 
 * @author            : Mark Moser
 * @group             : 
 * @last modified on  : 02-21-2023
 * @last modified by  : Mark Moser
 * Modifications Log
 * Ver   Date         Author       Modification
 * 1.0   02-21-2023   Mark Moser   Initial Version
**/
@isTest
private class TestPermissionUtility {

    Static testmethod void test1(){

        permissionUtility.check('NQ01');


    }
}