@isTest
private class TestJSON {

Static testmethod void test1(){


	JSONSmartCommDocResponse.testRun();
	JSONSmartCommCustomerProposalDoc.testRun();
	JSONSmartCommProposalDoc.testRun();
	JSONSmartCommQuoteDoc.testRun();
	JSONPricingSubsidies.testRun();
	JSONPricingAssets.testRun();
	JSONPricingFinancialProduct.testRun();
	JSONPricingAsset.testRun();
	JSONPricingAssetType.testRun();
	JSONPricingProgram.testRun();
	JSONPricingMake.testRun();
	JSONCreditAppResponse.testRun();
	JSONPriceResults.testRun();
	JSONCreateCustomerResponse.testRun();
	JSONCreateCustomer.testRun();
	JSONPricingFinancialProducts.testRun();
	JSONSmartCommDocRequest.testRun();
	JSONSubmitCreditAppRequest.testRun();
	JSONPricingPriceRequest.testRun();



}
}